Repository ashleve/lightning-hydra-template, pull requests merged in 2022-09, with the labels that each got.

#426 Fix logging metrics in DDP mode
  src/models/mnist_module.py
Labels: bug

#427 Add shellcheck linter
  .pre-commit-config.yaml
Labels: enhancement

#441 Update comments
  src/eval.py
  src/train.py
Labels: cosmetic

#442 Update readme
  README.md
Labels: cosmetic

#444 fix broken link of datamodule
  src/datamodules/mnist_datamodule.py
Labels: cosmetic
