Repository ashleve/lightning-hydra-template, pull requests merged in 2022-12, with the labels that each got.

#473 Fix deprecated TPU import
  tests/helpers/package_available.py
Labels: bug

#474 Move testing on macos to separate github workflow task
  .github/workflows/test.yml
Labels: enhancement

#475 Add `task` and `num_classes` args to accuracy metric
  requirements.txt
  src/models/mnist_module.py
Labels: bug

#476 Improve comments
  src/eval.py
  src/train.py
Labels: documentation, cosmetic

#479 send hparams to all loggers
  src/utils/utils.py
Labels: bug

#480 Upgrade to hydra 1.3
  requirements.txt
  src/eval.py
  src/train.py
Labels: dependencies

#482 Remove debug from makefile
  Makefile
Labels: cosmetic, best-practices

#483 Improve utils warnings
  src/utils/utils.py
Labels: cosmetic

#481 Fix loading MNISTLitModule from ckpt
  src/models/mnist_module.py
Labels: refactoring

#486 Add explicit comment/warning to `training_epoch_end()`
  src/models/mnist_module.py
Labels: cosmetic, best-practices

#484 Add `codecov.yml` to prevent failing pipeline on coverage decrease
  .github/codecov.yml
  .github/workflows/test.yml
Labels: enhancement

#488 Refactor `task_wrapper` decorator
  src/utils/utils.py
Labels: refactoring

#493 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement
