Repository ashleve/lightning-hydra-template, pull requests merged in 2023-03, with the labels that each got.

#532 Support for installing dependencies with conda
  .pre-commit-config.yaml
  README.md
  environment.yaml
Labels: enhancement

#539 Add `__init__.py` to `configs/` folder
  configs/__init__.py
  setup.py
Labels: enhancement

#543 Release v1.5.3
  .pre-commit-config.yaml
  README.md
  configs/__init__.py
  environment.yaml
  requirements.txt
  setup.py
  src/models/mnist_module.py
  tests/conftest.py
Labels: release

#534 Support for logging with aim.
  .gitignore
  configs/experiment/example.yaml
  configs/logger/aim.yaml
  requirements.txt
  src/utils/utils.py
Labels: enhancement

#549 Update pre-commit hooks
  .pre-commit-config.yaml
  README.md
  src/utils/utils.py
Labels: documentation, maintenance

#541 Refactor utils
  src/eval.py
  src/train.py
  src/utils/__init__.py
  src/utils/instantiatiators.py
  src/utils/logging_utils.py
  src/utils/utils.py
Labels: refactoring

#550 Add pytorch 2.0 model compilation
  configs/train.yaml
  src/train.py
Labels: enhancement

#551 Update `README.md`
  README.md
  environment.yaml
  src/train.py
Labels: documentation

#545 Release v2.0.0
  .gitignore
  .pre-commit-config.yaml
  README.md
  configs/callbacks/early_stopping.yaml
  configs/callbacks/model_checkpoint.yaml
  configs/callbacks/model_summary.yaml
  configs/callbacks/rich_progress_bar.yaml
  configs/experiment/example.yaml
  configs/logger/aim.yaml
  configs/logger/comet.yaml
  configs/logger/csv.yaml
  configs/logger/mlflow.yaml
  configs/logger/neptune.yaml
  configs/logger/tensorboard.yaml
  configs/logger/wandb.yaml
  configs/train.yaml
  configs/trainer/default.yaml
  environment.yaml
  requirements.txt
  src/data/mnist_datamodule.py
  src/eval.py
  src/models/mnist_module.py
  src/train.py
  src/utils/__init__.py
  src/utils/instantiatiators.py
  src/utils/logging_utils.py
  src/utils/pylogger.py
  src/utils/rich_utils.py
  src/utils/utils.py
  tests/helpers/package_available.py
Labels: release

#557 fix(docs): fix dead link to lightning docs
  configs/callbacks/early_stopping.yaml
  configs/callbacks/model_checkpoint.yaml
  configs/callbacks/model_summary.yaml
  configs/callbacks/rich_progress_bar.yaml
Labels: bug
