Repository ashleve/lightning-hydra-template, pull requests merged in 2023-01, with the labels that each got.

#494 Update code examples in readme
  README.md
Labels: documentation

#497 Add `dev` branch to pr tests workflow
  .github/workflows/code-quality-pr.yaml
  .github/workflows/test.yml
Labels: maintenance

#496 Improve root setup
  .project-root
  configs/paths/default.yaml
  src/eval.py
  src/train.py
Labels: refactoring, maintenance

#498 Refactor tests
  tests/conftest.py
  tests/test_datamodules.py
Labels: refactoring, maintenance

#499 Update `README.md`
  README.md
Labels: documentation

#502 Remove object instantiation from `__main__` methods
  src/data/mnist_datamodule.py
  src/models/mnist_module.py
  src/utils/rich_utils.py
Labels: maintenance

#503 Add PR authors to release draft config
  .github/release-drafter.yml
Labels: maintenance

#504 Release 1.5.1
  .github/release-drafter.yml
  .github/workflows/code-quality-pr.yaml
  .github/workflows/test.yml
  .gitignore
  .project-root
  README.md
  configs/data/mnist.yaml
  configs/debug/default.yaml
  configs/eval.yaml
  configs/experiment/example.yaml
  configs/hparams_search/mnist_optuna.yaml
  configs/paths/default.yaml
  configs/train.yaml
  src/data/__init__.py
  src/data/components/__init__.py
  src/data/mnist_datamodule.py
  src/eval.py
  src/models/mnist_module.py
  src/train.py
  src/utils/rich_utils.py
  src/utils/utils.py
  tests/conftest.py
  tests/test_configs.py
  tests/test_datamodules.py
Labels: release
