Repository ashleve/lightning-hydra-template, pull requests merged in 2023-05, with the labels that each got.

#571 Set strategy to `ddp` in ddp config
  configs/trainer/ddp.yaml
Labels: bug

#572 Set `sync_dist=True` when logging best so far validation accuracy
  src/models/mnist_module.py
Labels: best-practices, maintenance

#573 Release 2.0.2
  configs/trainer/ddp.yaml
  src/models/mnist_module.py
Labels: release

#575 Lightning + Aim dependency fix in conda environment.yaml and setup.py.
  environment.yaml
  setup.py
Labels: maintenance
