Repository ashleve/lightning-hydra-template, pull requests merged in 2023-07, with the labels that each got.

#584 Removing yaml extension from hydra config names in defaults lists.
  configs/callbacks/default.yaml
  configs/debug/fdr.yaml
  configs/debug/limit.yaml
  configs/debug/overfit.yaml
  configs/debug/profiler.yaml
  configs/eval.yaml
  configs/experiment/example.yaml
  configs/logger/many_loggers.yaml
  configs/train.yaml
  configs/trainer/cpu.yaml
  configs/trainer/ddp.yaml
  configs/trainer/ddp_sim.yaml
  configs/trainer/gpu.yaml
  configs/trainer/mps.yaml
Labels: best-practices

#589 Docstrings revamp.
  .pre-commit-config.yaml
  src/data/mnist_datamodule.py
  src/eval.py
  src/models/components/simple_dense_net.py
  src/models/mnist_module.py
  src/train.py
  src/utils/instantiators.py
  src/utils/logging_utils.py
  src/utils/pylogger.py
  src/utils/rich_utils.py
  src/utils/utils.py
  tests/conftest.py
  tests/helpers/package_available.py
  tests/helpers/run_if.py
  tests/helpers/run_sh_command.py
  tests/test_configs.py
  tests/test_datamodules.py
  tests/test_eval.py
  tests/test_sweeps.py
  tests/test_train.py
Labels: enhancement, best-practices

#592 Rename `pyrootutils` to `rootutils`
  environment.yaml
  requirements.txt
  src/eval.py
  src/train.py
  tests/conftest.py
Labels: dependencies

#588 Fixes colorlog issue where train.log is saved in project root dir
  configs/hydra/default.yaml
Labels: bug
