Repository ashleve/lightning-hydra-template, pull requests merged in 2023-02, with the labels that each got.

#517 fix use of deprecated LightningLoggerBase class
  src/eval.py
  src/train.py
  src/utils/utils.py
Labels: maintenance

#515 Hotfix for isort poetry incompatibility
  .pre-commit-config.yaml
Labels: maintenance

#523 Deprecate Python 3.7
  .github/workflows/test.yml
Labels: maintenance

#524 Update `README.md`
  README.md
Labels: documentation

#521 Release v1.5.2
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  requirements.txt
  src/eval.py
  src/train.py
  src/utils/utils.py
Labels: release

#542 Set hydra version to 1.3 in tests
  tests/conftest.py
Labels: maintenance

#540 Encourage resetting all validation metrics when training starts
  src/models/mnist_module.py
Labels: enhancement
